# Generated by Django 3.0.6 on 2020-05-27 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0002_auto_20200527_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joggingsession',
            name='dn_speed',
            field=models.DecimalField(decimal_places=1, default=0, editable=False, max_digits=3, verbose_name='calculated speed (km/h)'),
        ),
        migrations.AlterField(
            model_name='joggingsession',
            name='dn_week',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=6, verbose_name='calculated calendar week (YYYY.WW)'),
        ),
    ]
