# Generated by Django 3.0.6 on 2020-05-30 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0003_auto_20200527_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='joggingsession',
            name='lu_weather',
            field=models.TextField(blank=True, verbose_name='weather'),
        ),
        migrations.AddField(
            model_name='joggingsession',
            name='lu_weather_location',
            field=models.TextField(blank=True, verbose_name='location (for weather)'),
        ),
        migrations.AlterField(
            model_name='joggingsession',
            name='dn_week',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
