# Generated by Django 3.0.6 on 2020-05-31 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0004_auto_20200530_1750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joggingsession',
            options={'ordering': ('start',)},
        ),
        migrations.AlterField(
            model_name='joggingsession',
            name='lu_weather',
            field=models.TextField(blank=True, editable=False, verbose_name='weather'),
        ),
        migrations.AlterField(
            model_name='joggingsession',
            name='lu_weather_location',
            field=models.TextField(blank=True, default='', verbose_name='location (for weather)'),
        ),
    ]
