# Generated by Django 3.0.6 on 2020-05-31 11:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jogging', '0005_auto_20200531_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joggingsession',
            name='dn_week',
            field=models.IntegerField(default=0, editable=False, verbose_name='calendar week (yyyyww)'),
        ),
        migrations.AlterField(
            model_name='joggingsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jogging_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
