# Generated by Django 3.0.6 on 2020-06-04 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jogging', '0006_auto_20200531_1127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='joggingsession',
            options={'ordering': ('-start', 'id')},
        ),
        migrations.RemoveField(
            model_name='joggingsession',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='joggingsession',
            name='is_in_report',
        ),
    ]
